### ISSUE TITLE
JSON-LD add link to original stac metadata, and link to HTML landing page

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/stacIndexer#16]
Community will be adding links to the  metadata and landing page.
These need to go into the dataset landing page

**Comment by addelany** [comment]
@ylyangtw  I have updated the JSON files to include a link to the rendered STAC instance and a link to the raw JSON file on GitHub. These are stored in the JSON files as `link` objects, similar to the model code link and other items you have mapped to the GeoCodes. I also have the option to store these as `asset` items, rather than `link` items so please let me know if that is preferred.

Here is an example of the current format from one of the JSONS. Please let me know if this works for you.

`"links": [
  ....
  
    {
      "rel": "item",
      "href": "https://github.com/eco4cast/neon4cast-ci/blob/main/baseline_models/models/aquatics_persistenceRW.R",
      "type": "text/html",
      "title": "Link for Model Code"
    },
    {
      "rel": "item",
      "href": "https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/eco4cast/neon4cast-ci/main/catalog/forecasts/Aquatics/Daily_Chlorophyll_a/models/climatology.json",
      "type": "text/html",
      "title": "Link for rendered STAC item"
    },
    {
      "rel": "item",
      "href": "https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/catalog/forecasts/Aquatics/Daily_Chlorophyll_a/models/climatology.json",
      "type": "text/html",
      "title": "Link for raw JSON file"
    }
  ]`

**Comment by ylyangtw** [comment]
close as it's done
